// Generated by http://www.jsonschema2pojo.org

package de.hdm_stuttgart.mi.sd1.weather.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
  "dt",
  "main",
  "weather",
  "clouds",
  "wind",
  "sys",
  "dt_txt",
  "rain"
})
public class List {

  @JsonProperty("dt")
  private int dt;
  @JsonProperty("main")
  private Main main;
  @JsonProperty("weather")
  private java.util.List<WeatherData> weather = null;
  @JsonProperty("clouds")
  private Clouds clouds;
  @JsonProperty("wind")
  private Wind wind;
  @JsonProperty("sys")
  private Sys sys;
  @JsonProperty("dt_txt")
  private String dtTxt;
  @JsonProperty("rain")
  private Rain rain;
  /**
   * No args constructor for use in serialization
   */
  public List() {
  }

  /**
   * @param clouds Sky's state of clouds
   * @param dt Date and time
   * @param wind State of wind
   * @param sys Internal API parameter
   * @param dtTxt Localized human readable date and time
   * @param weather List of weather forcasts
   * @param rain State of rain
   * @param main Global temperature, humidity etc. parameter
   */
  public List(int dt, Main main, java.util.List<WeatherData> weather, Clouds clouds, Wind wind, Sys sys, String dtTxt, Rain rain) {
    super();
    this.dt = dt;
    this.main = main;
    this.weather = weather;
    this.clouds = clouds;
    this.wind = wind;
    this.sys = sys;
    this.dtTxt = dtTxt;
    this.rain = rain;
  }

  @JsonProperty("dt")
  public int getDt() {
    return dt;
  }

  @JsonProperty("dt")
  public void setDt(int dt) {
    this.dt = dt;
  }

  @JsonProperty("main")
  public Main getMain() {
    return main;
  }

  @JsonProperty("main")
  public void setMain(Main main) {
    this.main = main;
  }

  @JsonProperty("weather")
  public java.util.List<WeatherData> getWeather() {
    return weather;
  }

  @JsonProperty("weather")
  public void setWeather(java.util.List<WeatherData> weather) {
    this.weather = weather;
  }

  @JsonProperty("clouds")
  public Clouds getClouds() {
    return clouds;
  }

  @JsonProperty("clouds")
  public void setClouds(Clouds clouds) {
    this.clouds = clouds;
  }

  @JsonProperty("wind")
  public Wind getWind() {
    return wind;
  }

  @JsonProperty("wind")
  public void setWind(Wind wind) {
    this.wind = wind;
  }

  @JsonProperty("sys")
  public Sys getSys() {
    return sys;
  }

  @JsonProperty("sys")
  public void setSys(Sys sys) {
    this.sys = sys;
  }

  @JsonProperty("dt_txt")
  public String getDtTxt() {
    return dtTxt;
  }

  @JsonProperty("dt_txt")
  public void setDtTxt(String dtTxt) {
    this.dtTxt = dtTxt;
  }

  @JsonProperty("rain")
  public Rain getRain() {
    return rain;
  }

  @JsonProperty("rain")
  public void setRain(Rain rain) {
    this.rain = rain;
  }
}