// Generated by http://www.jsonschema2pojo.org

package de.hdm_stuttgart.mi.sd1.weather.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
  "temp",
  "temp_min",
  "temp_max",
  "pressure",
  "sea_level",
  "grnd_level",
  "humidity",
  "temp_kf"
})
public class Main {

  @JsonProperty("temp")
  private double temp;
  @JsonProperty("temp_min")
  private double tempMin;
  @JsonProperty("temp_max")
  private double tempMax;
  @JsonProperty("pressure")
  private double pressure;
  @JsonProperty("sea_level")
  private double seaLevel;
  @JsonProperty("grnd_level")
  private double grndLevel;
  @JsonProperty("humidity")
  private int humidity;
  @JsonProperty("temp_kf")
  private int tempKf;

  /**
   * No args constructor for use in serialization
   */
  public Main() {
  }

  /**
   * @param seaLevel
   * @param humidity
   * @param pressure
   * @param grndLevel
   * @param tempMax
   * @param temp
   * @param tempKf
   * @param tempMin
   */
  public Main(double temp, double tempMin, double tempMax, double pressure, double seaLevel, double grndLevel, int humidity, int tempKf) {
    super();
    this.temp = temp;
    this.tempMin = tempMin;
    this.tempMax = tempMax;
    this.pressure = pressure;
    this.seaLevel = seaLevel;
    this.grndLevel = grndLevel;
    this.humidity = humidity;
    this.tempKf = tempKf;
  }

  @JsonProperty("temp")
  public double getTemp() {
    return temp;
  }

  @JsonProperty("temp")
  public void setTemp(double temp) {
    this.temp = temp;
  }

  @JsonProperty("temp_min")
  public double getTempMin() {
    return tempMin;
  }

  @JsonProperty("temp_min")
  public void setTempMin(double tempMin) {
    this.tempMin = tempMin;
  }

  @JsonProperty("temp_max")
  public double getTempMax() {
    return tempMax;
  }

  @JsonProperty("temp_max")
  public void setTempMax(double tempMax) {
    this.tempMax = tempMax;
  }

  @JsonProperty("pressure")
  public double getPressure() {
    return pressure;
  }

  @JsonProperty("pressure")
  public void setPressure(double pressure) {
    this.pressure = pressure;
  }

  @JsonProperty("sea_level")
  public double getSeaLevel() {
    return seaLevel;
  }

  @JsonProperty("sea_level")
  public void setSeaLevel(double seaLevel) {
    this.seaLevel = seaLevel;
  }

  @JsonProperty("grnd_level")
  public double getGrndLevel() {
    return grndLevel;
  }

  @JsonProperty("grnd_level")
  public void setGrndLevel(double grndLevel) {
    this.grndLevel = grndLevel;
  }

  @JsonProperty("humidity")
  public int getHumidity() {
    return humidity;
  }

  @JsonProperty("humidity")
  public void setHumidity(int humidity) {
    this.humidity = humidity;
  }

  @JsonProperty("temp_kf")
  public int getTempKf() {
    return tempKf;
  }

  @JsonProperty("temp_kf")
  public void setTempKf(int tempKf) {
    this.tempKf = tempKf;
  }
}